# Add official climb data fields
#
# Revision ID: 20260222_0003
# Revises: 20260219_0002
# Create Date: 2026-02-22 20:45:00.000000
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '20260222_0003'
down_revision: Union[str, None] = '20260219_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_match_findings', sa.Column('official_climb_level', sa.String(), nullable=True))
    op.add_column('team_match_findings', sa.Column('climb_data_source', sa.String(), nullable=True))
    op.add_column('team_match_findings', sa.Column('climb_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_match_findings', 'climb_confidence')
    op.drop_column('team_match_findings', 'climb_data_source')
    op.drop_column('team_match_findings', 'official_climb_level')
    # ### end Alembic commands ###
